sudo: required
services:
    - docker

before_install:
    - docker build -t kylemartincollins/docker-react1 -f Dockerfile.dev .

script:
  - docker run kylemartincollins/docker-react1 npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-160941564650"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"